name: chatto
version: 1.0.0+1
publish_to: none
description: chatto is connection people
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.16
  lottie: ^2.3.0
  introduction_screen: ^3.1.7
  avatar_glow: 2.0.2
  flutter: 
    sdk: flutter
  emoji_picker_flutter: ^1.5.2
  google_sign_in: ^6.0.2
  get_storage: ^2.1.1
  cloud_firestore: ^4.4.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/lottie/
  uses-material-design: true

