name: chatto
version: 1.0.0+1
publish_to: none
description: chatto is connection people
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.16
  lottie: ^2.3.0
  introduction_screen: ^3.1.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/lottie/

