### HEALTH FACILITY GET ALL
GET http://localhost:8080/api/v1/healthfacilities
Content-Type: application/json

### HEALTH FACILITY GET BY NAME
GET http://localhost:8080/api/v1/healthfacilities/:name
Content-Type: application/json

### HEALTH FACILITY CREATE
POST http://localhost:8080/api/v1/healthfacilities
Content-Type: application/json

{
  "email": "rsbangga@gmail.com",
  "email_admin": "admin@gmail.com",
  "password_admin": "admin@gmail.com",
  "phonenum": "08123456789",
  "name": "Rumah Sakit Bangga",
  "image": "",
  "current_address": "Jl Bangga",
  "district": "CWG",
  "city": "Kuningan",
  "province": "Jawa Barat",
  "latitude": "123",
  "longtitude": "321"
}

### HEALTH FACILITY ADMIN UPDATE HEALTH FACILITY
PUT http://localhost:8080/api/v1/admin/healthfacilities
Content-Type: application/json

{
  "email": "rsbangga@gmail.com",
  "phonenum": "08123456789",
  "name": "Rumah Sakit Bangga",
  "image": "",
  "current_address": "Jl Bangga",
  "district": "CWG",
  "city": "Kuningan",
  "province": "Jawa Barat",
  "latitude": "123",
  "longtitude": "321"
}

### HEALTH FACILITY ADMIN DELETE HEALTH FACILITY
DELETE http://localhost:8080/api/v1/admin/healthfacilities/:id
Content-Type: application/json


