### HISTORY DASHBOARD
GET http://localhost:8080/api/v1/dashboard/history
Content-Type: application/json

### HISTORY ADMIN CREATE
POST http://localhost:8080/api/v1/admin/histories
Content-Type: application/json

### HISTORY ADMIN GET ALL
GET http://localhost:8080/api/v1/admin/histories
Content-Type: application/json

{
  "id_booking": 1,
  "nik": "1234567890123456"
}

### HISTORY ADMIN GET HISTORY BY ID
GET http://localhost:8080/api/v1/admin/histories/:id
Content-Type: application/json

### HISTORY ADMIN UPDATE HISTORY
PUT http://localhost:8080/api/v1/admin/histories/:id
Content-Type: application/json

{
  "id_history": 1,
  "nik": "1234567890123456",
  "status": "ok"
}
