### SESSION GET ACTIVE
GET http://localhost:8080/api/v1/dashboard/sessions
Content-Type: application/json

### SESSION GET FINISHED COUNT
GET http://localhost:8080/api/v1/dashboard/sessions/amount
Content-Type: application/json

### SESSION ADMIN GET ALL
GET http://localhost:8080/api/v1/admin/sessions/all
Content-Type: application/json

### SESSION ADMIN GET ALL BY ADMIN
GET http://localhost:8080/api/v1/admin/sessions
Content-Type: application/json

### SESSION ADMIN GET ALL BY ID
GET http://localhost:8080/api/v1/admin/sessions/:id
Content-Type: application/json

### SESSION ADMIN CREATE
POST http://localhost:8080/api/v1/admin/sessions
Content-Type: application/json

{
  "id_vaccine": 1,
  "session_name": "session 1",
  "capacity": 200,
  "date": "2023-06-08",
  "start": "08:00",
  "end": "12:00"
}

### SESSION ADMIN UPDATE
PUT http://localhost:8080/api/v1/admin/sessions/:id
Content-Type: application/json

{
  "id_vaccine": 1,
  "session_name": "session 1",
  "capacity": 200,
  "date": "2023-06-08",
  "start": "08:00",
  "end": "12:00"
}

### SESSION ADMIN CLOSED
PUT http://localhost:8080/api/v1/admin/sessions/:id/close
Content-Type: application/json

{
  "is_close": true
}

### SESSION ADMIN DELETE
DELETE http://localhost:8080/api/v1/admin/sessions/:id
Content-Type: application/json

### SESSION USER GET ALL OWN SESSION
GET http://localhost:8080/api/v1/users/sessions
Content-Type: application/json

### SESSION USER GET OWN SESSION BY ID
GET http://localhost:8080/api/v1/users/sessions/:id
Content-Type: application/json
