name: sewakantor
description: Sewa Kantor mobile application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  no_context_navigation: ^3.0.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  faker: ^2.1.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  email_validator: ^2.1.17
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  animated_splash_screen: ^1.3.0
  intl: ^0.18.1
  provider: ^6.0.5
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  image_picker: ^1.0.4
  flutter_polyline_points: ^2.0.0
  dio: ^5.3.3
  barcode_widget: ^2.0.4
  webview_flutter: ^4.4.1
  geocoding: ^2.1.0
  url_launcher: ^6.1.14
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg_assets/
    - assets/svg_assets/icons/
    - assets/image_assets/
    - assets/image_assets/beverages_image/
    - assets/image_assets/promo_image/
    - assets/image_assets/space_image/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
